```{r}
source("Rscripts/Fire-peak-df.R")
library("ggvenn")
```


```{r}
fuzz=0

dnase_not_fire = dnase_peaks %>%
    bed_merge() %>%
    bed_map(
        fire_df,
        is_fire_peak = n() > 0
    ) %>%
    replace_na(list(is_fire_peak = FALSE)) %>%
    filter(!is_fire_peak) %>%
    select(chrom,start,end)

ctcf_peaks_not_fire_not_dnase = ctcf_peaks_df %>%
    bed_merge() %>%
    bed_map(
        fire_df,
        is_fire_peak = n() > 0
    ) %>%
    bed_map(
        dnase_peaks,
        is_dnase_peak = n() > 0
    ) %>%
    replace_na(list(is_fire_peak = FALSE, is_dnase_peak=FALSE)) %>%
    filter(!is_fire_peak, !is_dnase_peak) %>%
    select(chrom,start,end)

atac_peaks_not_fire_not_dnase_not_ctcf = atac_peaks %>%
    bed_merge() %>%
    bed_map(
        fire_df,
        is_fire_peak = n() > 0
    ) %>%
    bed_map(
        dnase_peaks,
        is_dnase_peak = n() > 0
    ) %>%
    bed_map(
        ctcf_peaks_df,
        is_ctcf_peak = n() > 0
    ) %>%
    replace_na(list(is_fire_peak = FALSE, is_dnase_peak=FALSE, is_ctcf_peak=FALSE)) %>%
    filter(!is_fire_peak, !is_dnase_peak, !is_ctcf_peak) %>%
    select(chrom,start,end)

data_for_ven = bind_rows(
    list(
        CTCF = ctcf_peaks_not_fire_not_dnase,
        DNase = dnase_not_fire,
        FIRE = fire_df %>% select(chrom,start,end),
        ATAC = atac_peaks_not_fire_not_dnase_not_ctcf
    ),
    .id = "call"
) %>%
    mutate(
        start = start - fuzz,
        end = end + fuzz
    ) %>%
    bed_map(
        unreliable_df,
        is_unreliable = n() > 0 
    ) %>%
    bed_map(
        SDs,
        is_SD = n() > 0
    ) %>%
    bed_map(
        blacklist_df,
        is_blacklist = n() > 0
    ) %>%
    bed_map(
        dnase_peaks,
        is_dnase_peak = n() > 0
    ) %>%
    bed_map(
        fire_df,
        is_fire_peak = n() > 0
    ) %>%
    bed_map(
        ctcf_peaks_df,
        is_ctcf_peak = n() > 0
    ) %>%
    bed_map(
        atac_peaks,
        is_atac_peak = n() > 0
    ) %>%
    replace_na(
        list(
            is_unreliable = FALSE,
            is_SD = FALSE,
            is_dnase_peak = FALSE,
            is_fire_peak = FALSE,
            is_ctcf_peak = FALSE,
            is_atac_peak = FALSE,
            is_blacklist = FALSE
        )
    ) %>%
    data.table()


filtered_data_for_ven = data_for_ven %>%
    filter(is_fire_peak | !is_unreliable) %>%
    filter(!is_SD) %>%
    filter(!is_blacklist) %>%
    select(-is_unreliable, -is_SD, -is_blacklist) %>%
    filter(chrom %in% FAI$chrom) %>%
    filter(chrom != "chrM") %>%
    filter(chrom != "chrY") %>%
    filter(chrom != "chrEBV") 

filtered_data_for_ven %>%
    group_by(call) %>%
    summarise(
        n_fire_peaks = sum(is_fire_peak),
        n_dnase_peaks = sum(is_dnase_peak),
        n_ctcf_peaks = sum(is_ctcf_peak),
        n_atac_peaks = sum(is_atac_peak)
    )

n_dnase_peaks = data_for_ven %>% filter(call == "DNase", !is_unreliable, !is_SD) %>% nrow()
n_fire_peaks = data_for_ven %>% filter(call == "Fire", !is_SD) %>% nrow()
n_shared_peaks = data_for_ven %>% filter(call=="Fire", is_dnase_peak, !is_SD) %>% nrow()
n_fire_only = n_fire_peaks - n_shared_peaks
n_dnase_only = n_dnase_peaks - n_shared_peaks


print(glue("n_fire_peaks: {n_fire_peaks}\nn_dnase_peaks: {n_dnase_peaks}\nn_shared_peaks: {n_shared_peaks}\nn_fire_only: {n_fire_only}\nn_dnase_only: {n_dnase_only}"))
```

```{r}
sum(filtered_data_for_ven$is_fire_peak)
sum(filtered_data_for_ven$is_dnase_peak)
sum(filtered_data_for_ven$is_ctcf_peak)

data.table(table(filtered_data_for_ven[,c("is_fire_peak","is_dnase_peak","is_ctcf_peak")]))

asdf = filtered_data_for_ven %>%
    select(-chrom,-start,-end, -is_ctcf_peak) %>%
    filter(call != "CTCF") %>%
    ggvenn()
my_ggsave("Figures/venn-fire-dnase.pdf")
4asdf = filtered_data_for_ven %>%
    select(-chrom,-start,-end) %>%
    ggvenn() 
my_ggsave("Figures/venn-fire-dnase-ctcf.pdf", height=10, width=10)
```

```{r}
```

```{r}
sum(fire_df$is_ctcf_peak)
```