```{r}
source("Rscripts/Fire-peak-df.R")
```

# FDR vs SCORE
```{r}
fdr.df = fread("results/GM12878/FDR-peaks/FIRE.score.to.FDR.tbl") %>%
    pivot_longer(
        contains("peaks")
    ) %>% data.table()
myt.df = bind_rows(fdr.df[ which.min(abs(fdr.df$FDR-0.05)), ],
fdr.df[ which.min(abs(fdr.df$FDR-0.01)), ])

fdr.df %>%
    ggplot(aes(y=value/1e6, x=threshold, color=name)) +
    geom_line() +
    geom_vline(
        data=myt.df,
        aes(xintercept=threshold),
        linetype="dashed",
        size=.2,
    ) +
    scale_x_continuous("FIRE score threshold") + 
    scale_y_continuous("# of Mbp over FIRE score threshold", trans="log10", label=comma) + 
    scale_color_manual("",
        values=c(
            peaks="darkred",
            shuffled_peaks="darkgray"
        ),
        labels=c("Observed FIRE elements", "Shuffled FIRE elements")
    )+
    annotation_logticks(side="l", size=.2) + 
    my_grid() +
    theme(
        legend.position="top"
    )

my_ggsave("Figures/FIRE-score-vs-shuffled.pdf", height=2, width=2.5)
```

```{r}
fdr_vs_score = bind_rows(
    list(
        X130 = fread("results/GM12878/FDR-peaks/FIRE.score.to.FDR.tbl"),
        X30 = fread("results/30X_GM12878/FDR-peaks/FIRE.score.to.FDR.tbl")
    ),
    .id="id"
)

fdr_vs_score %>%
    mutate(
        FDR=-log10(FDR),
    ) %>%
    arrange(threshold) %>%
    ggplot(aes(x=threshold, y=FDR, color=id)) +
    scale_x_continuous("FIRE score threshold") + 
    scale_y_continuous("-log(FDR)", label=comma) + 
    geom_line()+
    scale_color_manual("",
        values=c("darkred","darkgray"),
        labels=c("130-fold Fiber-seq", "30-fold Fiber-seq")
    )+
    my_grid() +
    theme(
        legend.position="top"
    )
my_ggsave("Figures/FDR-vs-FIRE-score.pdf", height=2, width=2)
```