---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
# get a fire peak data table called `fire_df`
source("Rscripts/Fire-peak-df.R")

z=fire_df %>% 
    filter(!is.na(p_value)) %>%
    mutate(
        group=round(20*pmax(hap1_frac_acc, hap2_frac_acc))/20,
        group=case_when(
            group>0.9 ~ 0.0,
            TRUE ~ group
        )
    ) %>%
    filter(group>=0.1) %>%
    group_by(group) %>%
    summarise(
        val=100* sum(p_adjust <= 0.05) / n(),
        n()
    );z
z %>%
    ggplot(aes(x=group,y=val))+
    geom_point()+
    my_grid()
my_g%gsave("tmp.pdf", height=3, width=3)
    #merge(
    #    x %>% filter(encode_anno=="Lymphoid")
    #)
```

```{r}
pm = mean(fire_df$psize)
ps = sd(fire_df$psize)

z=fire_df %>%
    select(psize,group) %>%
    filter(psize<1000, psize>50) %>%
    data.frame %>%
    ggplot(aes(x=psize, y=factor(group))) + 
    geom_density_ridges2()+ 
    scale_y_discrete("Density of FIRE peak size for different % accessibility bins") +     # will generally have to set the `expand` option
    scale_x_continuous(
        "FIRE peak size (bp)",
        expand = c(0, 0),
        trans="log10",
        label=comma,
    ) +   # for both axes to remove unneeded padding
    ggtitle(glue("Mean peak size: {round(pm,1)} bp, SD: {round(ps,1)} bp")) +
    annotation_logticks(side="b")+
    coord_cartesian(clip = "off") + # to avoid clipping of the very top of the top ridgeline
    #theme_ridges() 
    my_hgrid()
my_ggsave("Figures/FIRE-peak-size.pdf", width=3, height=3)

```

```{r}
z=fire_df %>%
    #filter(!is_TSS) %>% 
    mutate(
        fire_max = fire_coverage/coverage,
    ) %>%
    # pivot longer on atac_max and fire_max
    pivot_longer(
        cols=c(fire_max, atac_max),
        names_to="seqtype",
        values_to="value"
    ) %>%
    group_by(seqtype, group) %>%
    mutate(
        n=seq(1,n()),
        psize=case_when(
            psize>1000 ~ 1000,
            #psize<50 ~ 50,
            TRUE ~ psize
        ),
    ) %>%
    #filter(n<=1000) %>%
    data.frame %>%
    ggplot(
        aes(
            x=value,
            #y=FIRE_size_mean,
            y=psize,
        )
    ) + 
    geom_hex(bins=100) + 
    stat_cor(
        aes(label = paste(after_stat(rr.label), after_stat(p.label), sep = "~`,`~")),
    ) + 
    scale_fill_distiller("", 
        palette = "Spectral", 
        trans="log10"
    ) +
    scale_y_continuous(
        "FIRE peak size (bp)",
        expand = c(0, 0),
        breaks = c(
            "50"=50, `250`=250, `500`=500, `750`=750, "+1,000"=1000
        ),
        #trans="log10",
        #label=comma,
    ) +   # for both axes to remove unneeded padding
    #annotation_logticks(side="l")+
    facet_col(~seqtype, scales="free_x")+
    scale_x_continuous(
        "FIRE actuation",
        #label=percent,
    ) +
    coord_cartesian(clip = "off") + # to avoid clipping of the very top of the top ridgeline
    #theme_ridges() 
    my_grid()
my_ggsave("Figures/FIRE-peak-size-vs-percent-acc.pdf", width=3, height=3)

```


```{r}
fire_df %>%
    filter(!has_variant) %>%
    select(
        chrom,start,end,ostart,oend,fire_coverage,coverage
    ) %>%
    rename(
        `#chrom` = chrom,
     ) %>%
    fwrite("Tables/FIRE-peak-size-no-variants.bed.gz", sep="\t")

```

```{r}
sd_df = fire_df %>% 
    select(FIRE_start_ssd, FIRE_end_ssd, group, is_ctcf_peak, TSS, is_cage_peak) %>%
    pivot_longer(
        cols=c(FIRE_start_ssd, FIRE_end_ssd),
        names_to="start_end",
        values_to="sd"
    ) %>%
    mutate(
        is_TSS = TSS > 0
    )
sd_df %>% 
    group_by(start_end) %>%
    dplyr::summarize(
        mean=mean(sd),
        median=median(sd),
    )
mean(sd_df$sd)

z=sd_df %>%
  ggplot(aes(x=sd+1)) + 
    geom_histogram(bins=100)+
    #geom_text(
    #    data = data.frame(x=mean(sd_df$sd), y=1000, label="Mean"),
    #    aes(x=x, y=y, label=comma(x)),
    #) +
    scale_x_continuous(
        "Standard deviation in start or end position\nof FIRE elements over a FIRE peak (bp)",
        #expand = c(0, 0),
        trans="log10",
        label=comma,
    ) +   # for both axes to remove unneeded padding
    annotation_logticks(side="b")+
    facet_col(~group < 0.10)+
    ggtitle(glue("Mean: {round(mean(sd_df$sd),1)} bp"))+
    #facet_col(~start_end)+
    coord_cartesian(xlim=c(10,1000))+
    my_hgrid()
my_ggsave("Figures/FIRE-peak-size-std-dev.pdf", width=3, height=2)
```

On average FIRE peaks are 208.9 bp long with a standard deviation of 67.7 bp; however, the elements of accessibility underlying these peaks will also vary in their start and end positions compared to the peak (standard deviation of 83.3 bp). 



```{r}
my_comparisons = list(
    c("TRUE FALSE", "FALSE TRUE")
)

z=sd_df %>%
  mutate(
    is_cage_peak = case_when(
        is_cage_peak ~ "CAGE peak",
        TRUE ~ "Not CAGE peak"
    ),
  ) %>%
  ggplot(aes(y=sd+1, x = paste(is_ctcf_peak, is_TSS))) + 
    geom_violin()+
    #geom_text(
    #    data = data.frame(x=mean(sd_df$sd), y=1000, label="Mean"),
    #    aes(x=x, y=y, label=comma(x)),
    #) +
    geom_text(
        data = . %>% group_by(is_ctcf_peak, is_TSS, is_cage_peak) %>% dplyr::summarize(mean=mean(sd), n=n()),
        aes(y=mean+1,
            label=paste0("n=", comma(n), "\nmean=" , round(mean,1)),
        ),
        size=1,
    )+
    stat_compare_means(comparisons = my_comparisons, size=1.5, method="wilcox.test")+
    scale_y_continuous(
        "Standard deviation in start or end position\nof FIRE elements over a FIRE peak (bp)",
        #expand = c(0, 0),
        trans="log10",
        label=comma,
    ) +   # for both axes to remove unneeded padding
    annotation_logticks(side="l")+
    facet_col(~is_cage_peak) +
    #coord_cartesian(ylim=c(10,1000))+
    my_grid()

my_ggsave("Figures/FIRE-peak-size-std-dev-facet.pdf", width=3, height=3)
```


# ORIENTED CAGE TSS deviations
```{r}
cage_tss_peaks = fire_df %>%
    filter(is_cage_tss) %>%
    filter(cage_tss_strand != ".") %>%
    filter(!is_ctcf_peak) %>%
    mutate(
        is_invariant = grepl("Tissue invariant", encode_anno)
    )
cage_tss_peaks %>%
    group_by(group, is_invariant) %>%
    summarise(
        mean(upstream_ssd),
        mean(downstream_ssd),
        n()
    )

asdf = cage_tss_peaks %>%
    #filter(group>0.5) %>%
    mutate(
        is_high = group>0.5,
    ) %>%
    pivot_longer(
        cols=c(upstream_ssd, downstream_ssd),
        names_to="type",
        values_to="sd"
    ) %>%
    ggplot(aes(y=sd+1,x=type)) +
    geom_violin(alpha=0.5)+
    geom_text(
        data = . %>% group_by(type,is_invariant) %>% dplyr::summarize(stat=median(sd), n=n()),
        aes(y=stat+1,
            label=paste0("n=", comma(n), "\nmedian=" , round(stat,1)),
        ),
        size=1,
    )+
    annotation_logticks(side="l")+
    facet_col(~is_invariant)+
    scale_y_continuous(
        "Standard deviation in start or end position\nof FIRE elements over a CAGE TSS (bp)",
        trans="log10",
        #limits=c(30,300),
    )+
    coord_cartesian(ylim=c(10,500))+
    my_hgrid()+
    theme(legend.position = "top")
my_ggsave("Figures/CAGE-TSS-orientation-deviation-in-fire-elements.pdf", height=3, width=4)
```
