```{r}
# napa region chr19:47,483,022-47,485,340

# movies that appear twice
#  m84039_230401_034725_s4
#  m84039_230401_031619_s3


bam="data/gm12878.napa.bam"
ft_cmd = glue('ft extract -F 2308 --all - -s {bam}')
ft_extract=fread(cmd=ft_cmd) %>%
    mutate(
        movie_name = gsub("/[0-9]+/ccs$", "", fiber),
        group = paste(movie_name, RG),
    ) %>%
    filter(RG != "GM12878_WGS") %>%
    filter(
        !(
            (movie_name %in% c("m84039_230401_034725_s4", "m84039_230401_031619_s3")) &
            (RG %in% c("GM12878", "GM12878_WGS"))
        )
    ) %>%
    unique() %>%
    data.table
table(ft_extract$RG)
nrow(ft_extract)
length(unique(ft_extract$fiber))

ft_cmd2 = glue('ft center -s --bed Tables/NAPA.bed {bam}')
napaz = fread(cmd=ft_cmd2) %>%
    mutate(
        movie_name = gsub("/[0-9]+/ccs$", "", query_name),
        group = paste(movie_name, RG),
    ) %>%
    filter(RG != "GM12878_WGS") %>%
    filter(
        !(
            (movie_name %in% c("m84039_230401_034725_s4", "m84039_230401_031619_s3")) &
            (RG %in% c("GM12878", "GM12878_WGS"))
        )
    ) %>%
    unique() %>%
    data.table

table(napaz$RG)
length(unique(ft_extract$fiber))
nrow(ft_extract)
```

```{r}
napa = napaz %>%
    merge(
        ft_extract %>% select(fiber, total_AT_bp, total_m6a_bp, RG, movie_name),
        by.x=c("query_name", "RG", "movie_name"), 
        by.y=c("fiber", "RG", "movie_name"),
    ) %>%
    group_by(RG, movie_name) %>%
    mutate(
        percent_m6a = 100*total_m6a_bp / total_AT_bp,        
        group_m6a = sum(total_m6a_bp)/sum(total_AT_bp),
        ave_msp_size = (centered_end - centered_start)[centered_position_type=="msp"] %>% mean,
        start = centered_start + centering_position,
        end = centered_end + centering_position, 
    ) %>%
    ungroup() %>%
    arrange(group_m6a, -percent_m6a) %>%
    mutate(
        query_name = factor(query_name, levels=unique(query_name)),
        row = as.numeric(query_name),
        group = factor(group, levels=unique(group)),
        # cut based on % m6a content
        m6a_name = cut(
            percent_m6a,
            breaks=seq(0,100),
        ),
    ) 

napa
table(napa$movie_name)
```


```{r}
zoom_by = -500
z=napa %>%
    #filter(abs(centered_start) < 2000) %>%
    filter(centered_position_type=="m6a" | centered_position_type=="nuc") %>%
    filter(centered_start < 2500 - zoom_by & centered_end > 0 + zoom_by) %>%
    ggplot(
        aes(
            xmin=start, xmax=end+1,
            ymin=row-0.4, ymax=row+0.4,
            fill=centered_position_type,
            alpha=centered_position_type,
        )
    ) +
    geom_rect() + 
    #geom_xsidehistogram(data = . %>% filter(centered_position_type=="m6a"),
    #    aes(x=start, group=NULL), binwidth=1) +
    scale_y_continuous(
        breaks = seq(0,1000),
        labels = rep("", 1001),
    ) + 
    scale_x_continuous(
        "Genomic position (NAPA promoter)",
        limits=c(47483022 + zoom_by, 47483022+2500 - zoom_by),
        labels = comma,
    ) +
    scale_fill_manual(
        values=c("m6a"="purple", "nuc"="gray")
    ) + 
    scale_alpha_manual(
        values=c("m6a"=1, "nuc"=0.5)
    ) +
    facet_col(~group, scales="free_y", space="free") +
    my_grid() + 
    theme(
        legend.position="none",
    )
my_ggsave("Figures/m6a-variation-napa.pdf", height=8, width=6)
```


```{r}


msps = ft_extract %>%
    filter(msp_starts!=".") %>%
    select(fiber, fiber_length, RG, msp_starts, msp_lengths, movie_name, group) %>%
    cSplit(c("msp_starts", "msp_lengths"), direction = "long", ) 


msps
# msp size by group
msps %>%
    group_by(group) %>%
    mutate(
        mean_msp_size = mean(msp_lengths),
        median = median(msp_lengths),
        sd_msp_size = sd(msp_lengths),
        n_msp = n(),
        frac_over_150 = sum(msp_lengths > 150) / n_msp,
        frac_1_bp = sum(msp_lengths == 1) / n_msp,
    ) %>%
    ungroup() %>%
    arrange(median, mean_msp_size) %>%
    mutate(
        group = factor(group, levels=unique(group)),
        msp_lengths = case_when(
            msp_lengths > 350 ~ 350,
            TRUE ~ msp_lengths
        )
    ) %>%
    ggplot(aes(x=msp_lengths, color=group)) +
    geom_step(aes(y=..density..), stat="bin", binwidth=5) +
    geom_vline(
        xintercept=150,
        linetype="dashed",
        color="black",
        linewidth=0.25,
    ) +
    geom_label(
        data = . %>% group_by(group) %>% summarise(stat=unique(frac_over_150)),
        aes(x=150, y=0, 
            label=paste0(
                percent(round(stat,3)),
                " > 150 bp"
            ),
        ),
        size = 2,
        alpha=0.5,
        color="black",
        hjust=0,
        vjust=-0.5,
    ) +
    geom_label(
        data = . %>% group_by(group) %>% summarise(stat=unique(frac_1_bp)),
        aes(x=1, y=0, 
            label=paste0(
                percent(round(stat,3)),
                " == 1 bp"
            ),
        ),
        size = 2,
        alpha=0.5,
        color="black",
        hjust=0,
        vjust=-5.5,
    ) +
    #geom_histogram(aes(y=after_stat(density)), bins=50, alpha=0) +
    scale_x_continuous(
        "MSP length",
        #trans="log10"
    ) +
    my_grid() +
    facet_wrap(~group, scales="free_y") +
    #coord_cartesian(clip="off") +
    theme(
        legend.position="none",
        # make x axis font size larger
        #axis.text.x = element_text(size=16),
        # make x axis label larger
        #axis.title.x = element_text(size=16),
        # make facet label text smaller
        strip.text = element_text(size=3),
    )
my_ggsave("Figures/m6a-variation-napa-msp-size.pdf", height=6, width=8)
```

# plot varing m6a / AT content
```{r}
t=ft_extract %>%
    mutate(
        percent_m6a = 100*total_m6a_bp / total_AT_bp,
    ) %>%
    group_by(group) %>%
    mutate(
        total_percent_m6a = sum(total_m6a_bp) / sum(total_AT_bp),
    ) %>%
    ungroup() %>%
    arrange(total_percent_m6a) %>%
    mutate(
        group = factor(group, levels=unique(group)),
    ) 

z = t %>%    
    ggplot(aes(x=percent_m6a, y=group)) +
    geom_violin(
        aes(weight = total_AT_bp),
       scale = "width" 
    ) +
    my_grid() +
    theme(
        legend.position="top",
    )
my_ggsave("Figures/m6a-variation-napa-m6a-percent-violin.pdf", height=3, width=6)

z = t %>%
    ggplot(aes(x=percent_m6a, color=group)) +
    #geom_step(aes(y=..density..), stat="bin", binwidth=0.1) +
    geom_density(adjust = 0.5) +
    scale_x_continuous(
        "Percent of A/T bp with m6A",
    ) +
    my_grid() +
    facet_wrap(~group, scales="free_y") +
    theme(
        legend.position="none",
        strip.text = element_text(size=3),
    )
my_ggsave("Figures/m6a-variation-napa-m6a-percent.pdf", height=6, width=6)
```

