```{r}
# get a fire peak data table called `df`
source("Rscripts/utils.R")
source("Rscripts//Fire-peak-df.R")
library(pROC)
```

```{r}
pos = fread("msp-vs-fire-roc-data/pos.msp.bed.gz")
neg = fread("msp-vs-fire-roc-data/neg.msp.bed.gz")

msp_fire_data = bind_rows(list(`1`=pos,`0`=neg), .id="label") %>%
    mutate(
        msp_len = V3 - V2,
        FDR = V10,
        fire_pred = 1 - FDR,
    ) %>% 
    # cannot be called fire
    filter(msp_len > 85) %>%
    # filter out nucs 
    filter(fire_pred >= 0 ) %>%
    select(label, msp_len, fire_pred, FDR) 

msp_fire_data %>% 
    group_by(label) %>%
    summarise(z=n()) %>%
    pivot_wider(names_from = label, values_from = z)

fire_roc = roc(msp_fire_data$label, msp_fire_data$fire_pred) 
msp_roc = roc(msp_fire_data$label, msp_fire_data$msp_len) 
```

```{r}
specificity_df = msp_fire_data %>%
    mutate(
        # round to nearest 25 
        msp_len = case_when(
            #msp_len >= 500 ~ round(msp_len/100)*100,
            TRUE ~ round(msp_len/10)*10,
        ),
    ) %>%
    #sample_n(10000) %>%
    select(-FDR) %>%
    pivot_longer(cols = c(msp_len, fire_pred)) %>%
    group_by(name, value) %>%
    summarise(
        n_ids = sum(label==1),
        n_total = n()
    ) %>%
    group_by(name) %>%
    arrange(-value, .by_group = TRUE) %>%
    filter(value > 0) %>%
    mutate(
        cum_n_ids = cumsum(n_ids),
        cum_n_total = cumsum(n_total),
        specificity = cum_n_ids/cum_n_total,
        n_fp = cum_n_total - cum_n_ids,
    ) %>%
    ungroup() %>%
    #arrange(-specificity, -value) %>%
    data.table

specificity_df %>%
    #filter(name!="msp_len") %>%
    #filter(specificity>=0.9)
    filter(cum_n_ids > 1e5) %>%
    data.table

```

```{r}
asdfasdf = specificity_df %>%
    filter(n_fp < 25e3) %>%
    filter(value < 1 | value >= 150) %>%
    #filter(n_total> 10 ) %>%
    ggplot(
        #aes(x=specificity, y=cum_n_ids, color=name),
        aes(x=n_fp, y=cum_n_ids, color=name),
    ) + 
    geom_line() +
    geom_point(size=0.5) +
    geom_text_repel(
        data = . %>% filter(n_fp >= 5000) %>% filter(value < 100 | value %% 50 == 0),
        aes(
            label=glue("TP={comma(cum_n_ids)}\nFP={comma(n_fp)}\nvalue={value}"),
        ),
        color="black",
        min.segment.length = 0,
        segment.alpha = 0.25,
        segment.size = 0.2,
        force=10,
        direction = "y",
        nudge_y=-1000,
        size=1,
        arrow = arrow(type = "closed", length = unit(0.02, "npc")),
    ) +
    #geom_bar(stat="identity")+
    my_grid() +
    scale_color_manual(
        "",
        labels=c(
            glue("FIRE prediction"),#; AUC=", round(fire_roc$auc,3)),
            glue("MSP length")#; AUC=", round(msp_roc$auc,3))
        ),
        values=c("darkred", "darkgrey")
    ) +
    scale_x_continuous(
        "Number of actuated regulatory elements outside of DHS sites\n(i.e. false positives)",
        label = scales::comma,
        #limits = c(0,10e3),
    ) +
    scale_y_continuous(
        "Number of actuated regulatory elements within DHS sites\n(i.e. true positives)",
        label = scales::comma
    ) +
    theme(
        legend.position="top"
    )
my_ggsave("Figures/msp-vs-fire-roc.pdf", height=3, width=3)
```


# fiber and MSP counts
```{r}
fire_counts = fread("30X_GM12878     6089875
CHM13   7414240
COLO_T_2_PS00_418_451_488       33976844
DSA_COLO_T_2_PS00_418_451_488   34699788
DSA_PS00338_COLO829BL_1 34544219
GM12878_bugged_coverage 32038887
GM12878 32006894
HG002   10138839
HG002_H1        4172314
HG002_H2        4371220
HG002v1.0.1     10270616
PS00272 14410015
PS00321 10992398
PS00327 15175621
PS00338_COLO829BL_1     34059151
PS00356_COLO829BL_2     35059045
PS00357_COLO829T_1      14042265
PS00381 5965587
PS00382 4690423
PS00383 7709965
PS00384 6674185
test_2024_02_23 285551
test    285207
test_large      1149296
UDN318336_PS00189       5732724
UDN633333_PS00115       8592249")
colnames(fire_counts) = c("sample", "fire_count")

fiber_counts = fread("30X_GM12878     5572071
CHM13   4751930
COLO_T_2_PS00_418_451_488       22304436
GM12878 24771424
HG002   10848421
HG002_H1        4417824
HG002_H2        4609070
HG002v1.0.1     10906135
PS00272 9634971
PS00321 4340193
PS00327 9611152
PS00338_COLO829BL_1     22511692
PS00356_COLO829BL_2     22304858
PS00357_COLO829T_1      8311132
PS00381 4417953
PS00382 3272185
PS00383 5600209
PS00384 4788907
test_2024_02_23 219644
test    241888
test_large      880404
UDN318336_PS00189       4530127
UDN633333_PS00115       7489013")
colnames(fiber_counts) = c("sample", "fiber_count")

fire_counts %>%
    merge(fiber_counts)

```