---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
# get a fire peak data table called `df`
source("Rscripts/Fire-peak-df.R")
```

```{r}
percent_encode = fire_df %>% 
    group_by(group) %>%
    summarise(
        `% in\nENCODE` = 100*mean(encode_count>0),
        `% in\nSDs`=100*mean(sd_count>0),
        `% in\nTSS`=100*mean(TSS>0),
        #`% of genome\n(c)`=100*sum(end-start)/3.1e9,
        `% of\ngenome\n(cumulative)`=100*max(Mbp*1e6)/3.1e9,
        `# of\npeaks`=n(),
        acc_percent=unique(group)+0.025,
        Mbp = sum(end-start)/1e6,
    ) %>%
    filter(`# of\npeaks` > 2)

cur_colors = c(
            `% in\nENCODE`="darkgreen",
            `% in\nTSS`="darkblue",
            `% in\nSDs`="darkred",
            `% of\ngenome\n(cumulative)`="darkgray",
            `# of\npeaks`="darkcyan"
            )
cur_colors
percent_encode_long = percent_encode %>%
    pivot_longer(
        cols=names(cur_colors)
        )

percent_encode_long

percent_plots = percent_encode_long %>%
    mutate(
        name=factor(name, levels=names(cur_colors))
    ) %>%
    ggplot(aes(x=acc_percent, y=value, group=name, fill=name)) +
    geom_bar(stat="identity", color="black")+
    geom_text(
        aes(
            x=acc_percent,
            label=sub("\\.0+$", "", comma(value, accuracy=0.01)),
        ),
        #min.segment.length=1,
        #direction="y",
        #alpha=0.5,
        vjust=-0.3,
        #color="white",
        #nudge_y=0.01,
        size=1
    ) +
    scale_y_continuous("", label=comma) +
    scale_x_continuous(
        "",
        breaks=seq(5,100,5)/100,
        label=rep("",20),
    )+
    scale_fill_manual(values=cur_colors) + 
    facet_col(~name, scales="free_y", strip.position = "left") + 
    my_grid() +
    coord_cartesian(xlim=c(0,1), clip=FALSE)+
    theme_no_x() +
    theme(legend.position="None")
```

```{r}
x = fire_df %>% 
    separate_rows(encode_anno, sep=";") %>%
    group_by(group, encode_anno) %>%
    summarise(
        count=n()   
    ) %>%
    group_by(
        group
    ) %>%
    filter(sum(count)>20) %>%
    mutate(
        percent=100*count/sum(count)
    ) %>%
    dplyr::group_by(encode_anno) %>%
    mutate(
        total_count=sum(count)
    ) %>%
    ungroup() %>%
    arrange(total_count) %>%
    mutate(
        encode_anno=factor(encode_anno, levels=unique(encode_anno))
    ) 

keep_annos = c("Lymphoid", "Tissue invariant", "Stromal B", "Primitive / embryonic", "Myeloid / erythroid")
fire_df %>% 
    separate_rows(encode_anno, sep=";") %>%
    mutate(
        encode_anno = case_when(
            encode_anno %in% keep_annos ~ encode_anno,
            TRUE ~ "Other"
        )
    ) %>%
    group_by(encode_anno) %>%
    summarise(
        count=n(),
        percent = count / nrow(fire_df) * 100 
    ) %>%
    fwrite(
        "Figures/peaks-vs-percent-encode-percents.txt",
        sep="\t",
    )

encode %>%
    group_by(component) %>%
    summarise(count=n(),percent = sum(end-start)/1e6) %>%
    mutate(
        #group="control",
        encode_anno=component,
        percent = percent/sum(percent)*100
    ) %>%
    arrange(percent) %>%
    merge(x, by="encode_anno") %>%
    filter(count.y>300) %>%
    data.table() %>%
    mutate(
        lfc = log2(percent.y) - log2(percent.x)
    ) %>%
    arrange(-lfc)


plot_encode_anno=x %>% 
    filter(!is.na(encode_anno)) %>%
    ggplot(
        aes(
            x=group+0.025,
            weight=count,
            fill=encode_anno,
        )
    ) +
    geom_bar(
        position="fill",
        width=0.0495,
    ) +
    scale_x_continuous(
        "",
        breaks=seq(5,100,5)/100,
        label=rep("",20),
    )+
    scale_y_continuous("")+
    scale_fill_manual(
        "", 
        values=as.vector(glasbey(length(unique(encode$component)))),
        guide=guide_legend(nrow=2)
    )+
    coord_cartesian(xlim=c(0,1))+
    my_grid()+
    theme(
        legend.text=element_text(size=3),
        legend.key.size=unit(1, "mm"),
        legend.position="top",
        plot.margin = unit(c(0, 0, 0, 0), "cm"),
    )
kk=plot_encode_anno+plot_spacer()+percent_plots+plot_layout(heights = c(1,-0.3, 3))
```


```{r}
by_5_per = fire_df %>%
    group_by(group) %>%
    slice_max(order_by = n, n = 1)

lookup=fire_df$Mbp
names(lookup)=fire_df$n
#lookup
my_scale_function=function(x){
    lookup[x]
}

pecdf=fire_df %>%
    arrange(-acc_percent, -n) %>%
    #filter((n+1)%%100==0) %>%
    ggplot(aes(x=acc_percent, y=n)) +
    geom_line()+
    geom_text_repel(
        data = fire_df %>% filter(n==max(n)),
        aes(
            x=min_percent_acc,
            label=paste(
                "Limit of detection", percent(min_percent_acc, accuracy=0.01),
                "\n# peaks", comma(n)
            ),
        ),
        min.segment.length=0,
        segment.size=0.2,
        direction="y",
        size=1.5,
        nudge_y=-1.0,
        #nudge_x=0.1,
    ) +
    geom_text_repel(
        data=by_5_per,
        aes(
            x=acc_percent,
            label=paste(
                comma(n)
            ),
        ),
        min.segment.length=0,
        direction="x",
        nudge_x=0.1,
        segment.size=0.1,
        size=1
    ) +
    scale_y_continuous(
        "# of regulatory elements\nin the genome",
        trans="log10",
        label=comma,
         # Add a second axis and specify its features
       #sec.axis = sec_axis(
       #     ~my_scale_function(.),
       #     name="Mbp",
       #     label=comma,
        #)
    ) + 
    annotation_logticks(side="l")+
    scale_x_continuous(
        "Minimum % of fibers that are accessible",
        breaks=seq(5,100,5)/100,
        label=percent,
        #guide = guide_axis(n.dodge = 2),
    ) +
    my_grid() +
    coord_cartesian(xlim=c(0,1), ylim=c(100,NA)) 



p=plot_encode_anno+plot_spacer()+percent_plots+pecdf+plot_layout(heights = c(1,-0.5, 3, 2))
my_ggsave("Figures/peaks-vs-percent.pdf", height=4, width=5)
```

