
```{r}
source("Rscripts/Fire-peak-df.R")
```

```{r}
sd_fire_df = fire_df %>%
    filter(is_SD) %>%
    replace_na(
        list(
            is_dnase_peak=F,
            is_atac_peak=F,
            SD_max_frac_match=0.88
        )
    ) %>% pivot_longer(cols=c(is_dnase_peak, is_atac_peak), names_to="peak_type", values_to="is_peak") 
    
sd_fire_df %>% group_by(peak_type) %>%
    summarise(
        n=n(),
        n_fire=sum(is_peak),
        percent_fire=mean(1-is_peak)
    )
```

```{r}
mean(fire_df$is_atac_peak==F)
mean(fire_df$is_dnase_peak!=T)
```

```{r}
asdfsad = sd_fire_df %>%
    mutate(
        is_peak = ifelse(is_peak, "Shared peak", "FIRE only peak"),
    ) %>%
    group_by(peak_type) %>%
    mutate(
        percent_fire = mean(is_peak=="FIRE only peak"),
        peak_type = ifelse(
            peak_type=="is_dnase_peak", 
            glue("Not DNase: ", round(100*unique(percent_fire),  2), "%"),
            glue("Not ATAC: ", round(100*unique(percent_fire),  2), "%")
        ),
    ) %>%
    ggplot(aes(x=SD_max_frac_match, fill=is_peak)) +
    geom_histogram(binwidth=0.005)+
    scale_x_continuous(
        "Percent identity of overlapping SDs",
        #trans="log10",
        label=percent,
    )+
    scale_y_continuous(
        "Number of peaks",
        #trans="log10"
    )+
    scale_fill_manual(
        "",
        values=c("darkred", "black")
    )+
    facet_col(~peak_type)+
    my_hgrid()+
    theme(legend.position = "top")
my_ggsave("Figures/SD-fire-peaks-hist.pdf", height=3, width=4)
```
